version: '3.5'

services:
  postgres:
    env_file:
      - ./.env
    container_name: postgres
    image: postgres:14.4-alpine
    command:
      - "postgres"
      - "-c"
      - "log_destination=stderr"
      - "-c"
      - "logging_collector=on"
      - "-c"
      - "log_directory=/var/lib/postgresql/data/pg_log"
      - "-c"
      - "work_mem=16MB"
      - "-c"
      - "maintenance_work_mem=512MB"
    restart: unless-stopped
    volumes:
      - ./postgres_db/postgres/postgresql-data:/var/lib/postgresql/data
      - ./postgres_db/postgres/pginit/:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    ports:
      - "5432:5432"

  telegram_bot:
    build: ./telegram_bot
    container_name: bot
    env_file:
      - ./telegram_bot/.env
    environment:
      POSTGRES_HOST: postgres
    volumes:
      - ./logs:/app/logs
    depends_on:
      - postgres
    restart: on-failure

  cryptopayments:
    container_name: cryptopayments
    build: cryptopayments
    command: uvicorn main:app --host 0.0.0.0
    env_file:
      - ./.env
    environment:
      POSTGRES_HOST: postgres
    ports:
      - '8000:8000'
    depends_on:
      - postgres
    restart: on-failure
